language: python
python:
  - "3.8"

services:
  - docker

before_script:
  - pip install docker-compose
  - cd GestionPersonnel/

script:
  - docker-compose run web python manage.py test

notifications:
  email:
    recipients:
      - wilfried.noubissie@facsciences-uy1.cm
    on_success: always
    on_failure: always