language: python

python:
  - "3.9"

services:
  - docker

before_script:
  - cd GestionPersonnel/
  - pip install docker-compose
  - docker-compose up -d

script:
  - docker exec gestionpersonnel_web_1 python manage.py test

after_script:
  - docker-compose down

notifications:
  email:
    recipients:
      - wilfried.noubissie@facsciences-uy1.cm
    on_success: always
    on_failure: always